global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
  
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']
  
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
